Add new translation for french
padloc/padloc pull request #542
Opened 2022-08-08 20:08 UTC by detobel36

2022-08-09 07:38 UTC, BrunoBernardino requested changes
Thank you so much for these @detobel36 ! I've made some suggestions to keep the formatting consistent (no spaces before marks, and ensure both the original and the translations match in terms of sentence-ending mark). I also caught what looked like a couple of typos, which you're welcome to not accept, if they're already correct.

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "Vous êtes sûr de vouloir rejeter cette invitation ?"
```suggestion
    "Vous êtes sûr de vouloir rejeter cette invitation?"
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "Invitation non trouvée"
```suggestion
    "Invitation non trouvée."
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "Vous avez déjà accepté cette invitation !"
```suggestion
    "Vous avez déjà accepté cette invitation!"
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "Cette invitation est expirée !"
```suggestion
    "Cette invitation est expirée!"
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "Veuillez entrer le code de confirmation qui vous a été fourni par le propriétaire de l'organisation !"
```suggestion
    "Veuillez entrer le code de confirmation qui vous a été fourni par le propriétaire de l'organisation!"
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "Êtes-vous sûr de vouloir supprimer cette invitation ?"
```suggestion
    "Êtes-vous sûr de vouloir supprimer cette invitation?"
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "{0} a bien été ajouté à votre organisation !"
```suggestion
    "{0} a bien été ajouté à votre organisation!"
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "Supprimer un élément"
```suggestion
    "Supprimer l'élément"
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "Cliquez ou déplacez les fichiers ici pour ajouter une pièce jointe !"
```suggestion
    "Cliquez ou déplacez les fichiers ici pour ajouter une pièce jointe!"
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "Êtes-vous sûr de vouloir supprimer ce champ ?"
```suggestion
    "Êtes-vous sûr de vouloir supprimer ce champ?"
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "Voulez-vous ajouter cet appareil comme périphérique de confiance ?"
```suggestion
    "Voulez-vous ajouter cet appareil comme périphérique de confiance?"
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "Nous n'avons pas réussi à vérifier votre adresse e-mail. Veuillez recommencer !"
```suggestion
    "Nous n'avons pas réussi à vérifier votre adresse e-mail. Veuillez recommencer!"
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "Mot de passe principal erroné. Veuillez réessayer !"
```suggestion
    "Mot de passe principal erroné. Veuillez réessayer!"
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "Erreur serveur."
```suggestion
    "Erreur de serveur."
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "Vous n'avez pas encore de compte Padloc 4 mais nous avons trouvé un compte d'une ancienne version. Voulez-vous migrer votre compte vers Padloc 4 maintenant ?"
```suggestion
    "Vous n'avez pas encore de compte Padloc 4 mais nous avons trouvé un compte d'une ancienne version. Voulez-vous migrer votre compte vers Padloc 4 maintenant?"
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "Votre compte et toutes les données associées ont été migrés avec succès ! Voulez-vous supprimer votre ancien compte maintenant ?"
```suggestion
    "Votre compte et toutes les données associées ont été migrés avec succès ! Voulez-vous supprimer votre ancien compte maintenant?"
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "C'est fait ! Veuillez noter que vous ne pourrez pas accéder à votre compte Padloc 4 avec les anciennes versions de l'application, donc assurez-vous d'avoir la dernière version installée sur tous
```suggestion
    "C'est fait ! Veuillez noter que vous ne pourrez pas accéder à votre compte Padloc 4 avec les anciennes versions de l'application, donc assurez-vous d'avoir la dernière version installée sur tous vos appareils! (Vous pouvez trouver les liens de téléchargement pour toutes les plateformes sur https://padloc.app/downloads/). Profitez de Padloc 4!"
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "Vous ne l'aimez pas ?"
```suggestion
    "Vous ne l'aimez pas?"
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "Votre mot de passe principal est le dernier mot de passe que vous aurez à retenir ! Mémorisez-le et ne le révélez jamais à personne, pas même à nous ! Nous vous recommandons de l'écrire sur un m
```suggestion
    "Votre mot de passe principal est le dernier mot de passe que vous aurez à retenir! Mémorisez-le et ne le révélez jamais à personne, pas même à nous! Nous vous recommandons de l'écrire sur un morceau de papier et de le conserver dans un endroit sûr, au moins jusqu'à ce que vous l'ayez mémorisé."
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "Tout est prêt !"
```suggestion
    "Tout est prêt!"
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "Votre compte a été créé avec succès. Profitez de l'utilisation de {0} !"
```suggestion
    "Votre compte a été créé avec succès. Profitez de l'utilisation de {0}!"
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "Un problème est survenu lors du traitement de votre demande. Veuillez réessayer plus tard !"
```suggestion
    "Un problème est survenu lors du traitement de votre demande. Veuillez réessayer plus tard!"
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "Etes-vous sûr de vouloir transférer la propriété de cette organisation à {0} ?"
```suggestion
    "Etes-vous sûr de vouloir transférer la propriété de cette organisation à {0}?"
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "La propriété de l'organisation a été transférée avec succès !"
```suggestion
    "La propriété de l'organisation a été transférée avec succès!"
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "Une version plus récente de {0} est nécessaire pour synchroniser ce coffre-fort. Veuillez effectuer la mise à jour vers la dernière version maintenant !"
```suggestion
    "Une version plus récente de {0} est nécessaire pour synchroniser ce coffre-fort. Veuillez effectuer la mise à jour vers la dernière version maintenant!"
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "Voulez-vous activer la synchronisation des répertoires via SCIM pour cette organisation ? Vous recevrez une URL unique à fournir à votre Active Directory ou à votre serveur LDAP pour la synchron
```suggestion
    "Voulez-vous activer la synchronisation des répertoires via SCIM pour cette organisation? Vous recevrez une URL unique à fournir à votre Active Directory ou à votre serveur LDAP pour la synchronisation et le provisionnement des membres."
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "Voulez-vous désactiver Directory Sync ? Vos membres ne seront plus synchronisés et provisionnés automatiquement."
```suggestion
    "Voulez-vous désactiver Directory Sync? Vos membres ne seront plus synchronisés et provisionnés automatiquement."
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "IMPORTANT, LIRE ATTENTIVEMENT: {0} est conçu de manière à ce qu'il nous soit impossible d'accéder aux données chiffré dans l'un de vos coffres-forts, même si nous le voulions. Bien que cela soit
```suggestion
    "IMPORTANT, LIRE ATTENTIVEMENT: {0} est conçu de manière à ce qu'il nous soit impossible d'accéder aux données chiffré dans l'un de vos coffres-forts, même si nous le voulions. Bien que cela soit essentiel pour assurer la sécurité de vos données, cela a également les implications suivantes:"
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "Les organisations suivantes vous appartiennent et seront supprimées en même temps que votre compte :"
```suggestion
    "Les organisations suivantes vous appartiennent et seront supprimées en même temps que votre compte:"
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "Êtes-vous sûr de vouloir désactiver le déverrouillage biométrique pour cet appareil ?"
```suggestion
    "Êtes-vous sûr de vouloir désactiver le déverrouillage biométrique pour cet appareil?"
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "Quel type d'authentification multi-facteurs souhaitez-vous ajouter ?"
```suggestion
    "Quel type d'authentification multi-facteurs souhaitez-vous ajouter?"
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "Êtes-vous sûr de vouloir supprimer cet authentificateur ?"
```suggestion
    "Êtes-vous sûr de vouloir supprimer cet authentificateur?"
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "Êtes-vous sûr de vouloir révoquer cette session ?"
```suggestion
    "Êtes-vous sûr de vouloir révoquer cette session?"
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "Êtes-vous sûr de vouloir supprimer cet appareil de vos appareils de confiance ?"
```suggestion
    "Êtes-vous sûr de vouloir supprimer cet appareil de vos appareils de confiance?"
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "Le test est réussi !"
```suggestion
    "Le test est réussi!"
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "Le test a échoué !"
```suggestion
    "Le test a échoué!"
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "Le test a échoué ! Erreur: {0}"
```suggestion
    "Le test a échoué! Erreur: {0}"
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "Êtes-vous sûr de vouloir révoquer le déverrouillage biométrique de l'appareil \"{0}\" ?"
```suggestion
    "Êtes-vous sûr de vouloir révoquer le déverrouillage biométrique de l'appareil \"{0}\"?"
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "Bon retour ! Veuillez entrer votre mot de passe principal pour déverrouiller l'application."
```suggestion
    "Bon retour! Veuillez entrer votre mot de passe principal pour déverrouiller l'application."
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "Veuillez entrer un nom du coffre-fort !"
```suggestion
    "Veuillez entrer un nom du coffre-fort!"
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "Nom du coffre-fort requis !"
```suggestion
    "Nom du coffre-fort requis!"
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "Veuillez entrer un autre nom de coffre-fort !"
```suggestion
    "Veuillez entrer un autre nom de coffre-fort!"
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "Nom réservé !"
```suggestion
    "Nom réservé!"
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "Veuillez affecter au moins un membre ou un groupe à ce coffre-fort !"
```suggestion
    "Veuillez affecter au moins un membre ou un groupe à ce coffre-fort!"
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "Coffre-fort supprimée avec succès !"
```suggestion
    "Coffre-fort supprimée avec succès!"
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "L'application n'a pas pu établir de connexion avec nos serveurs, veuillez vérifier votre connexion Internet ou réessayer plus tard !"
```suggestion
    "L'application n'a pas pu établir de connexion avec nos serveurs, veuillez vérifier votre connexion Internet ou réessayer plus tard!"
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "L'application n'a pas pu établir de connexion avec nos serveurs, veuillez vérifier votre connexion Internet ou réessayer plus tard !"
```suggestion
    "L'application n'a pas pu établir de connexion avec nos serveurs, veuillez vérifier votre connexion Internet ou réessayer plus tard!"
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "Vous n'avez pas d'éléments avec des mots de passe faibles !"
```suggestion
    "Vous n'avez pas d'éléments avec des mots de passe faibles!"
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "Vous n'avez pas d'éléments avec des mots de passe réutilisés !"
```suggestion
    "Vous n'avez pas d'éléments avec des mots de passe réutilisés!"
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "Vous n'avez pas d'éléments avec des mots de passe compromis !"
```suggestion
    "Vous n'avez pas d'éléments avec des mots de passe compromis!"
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "Vous n'avez pas d'éléments non sécurisés !"
```suggestion
    "Vous n'avez pas d'éléments non sécurisés!"
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "Le type d'authentification n'est pas pris en charge !"
```suggestion
    "Le type d'authentification n'est pas pris en charge!"
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "Certaines données associées à votre compte ont été enregistrées avec une version plus récente de Padloc et ne peuvent être décodées. Veuillez installer la dernière version de Padloc !"
```suggestion
    "Certaines données associées à votre compte ont été enregistrées avec une version plus récente de Padloc et ne peuvent être décodées. Veuillez installer la dernière version de Padloc!"
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
>      "Votre session est terminée. Veuillez vous reconnecter !"
```suggestion
    "Votre session est terminée. Veuillez vous reconnecter!"
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "Une nouvelle mise à jour est prête à être installée ! Voulez-vous l'installer maintenant ?"
```suggestion
    "Une nouvelle mise à jour est prête à être installée! Voulez-vous l'installer maintenant?"
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "Êtes-vous sûr de vouloir quitter cette page ? Toute modification sera perdue."
```suggestion
    "Êtes-vous sûr de vouloir quitter cette page? Toute modification sera perdue."
```

2022-08-09 07:38 UTC, BrunoBernardino commented on packages/locale/res/translations/fr.json
> +    "Ce nom de groupe n'est pas disponible !"
```suggestion
    "Ce nom de groupe n'est pas disponible!"
```

2022-08-09 07:54 UTC, detobel36 commented
@BrunoBernardino but in french they are space before marks 😕   So if you want to write "good french" you need to keep space.

For other remarks, I'm agree with you.  I will do the change this evening

2022-08-09 07:56 UTC, detobel36 commented on packages/locale/res/translations/fr.json
> +    "Erreur serveur."
Then it's better `Erreur du serveur.`

2022-08-09 19:13 UTC, detobel36 commented
I have made a fixup.
Before to "merge" I can "squash" commit (or you can do it).

2022-08-10 06:34 UTC, merged

2022-08-10 06:36 UTC, BrunoBernardino commented
Merci beaucoup @detobel36 !

2022-08-11 05:23 UTC, MaKleSoft commented
@detobel36 Thank you so much for your contribution! Are you twitter by any chance? Would like to give you a shout-out 😊

2022-08-11 05:31 UTC, detobel36 commented
Yes just "@Detobel36" on twitter 😉 

But thanks to you for this project !